[task.sleep]
command = "sleep"
args = ["2"]

[task.echo_hello]
command = "echo"
args = ["hello"]

[task.echo_bye]
command = "echo"
args = ["bye"]

[task.loop_1]
mode = "shell"
script = """
    for i in $(seq 1 10); do
        echo 1
        sleep 1
    done
"""

[task.loop_2]
mode = "shell"
script = """
    for i in $(seq 1 10); do
        echo 2
        sleep 1
    done
"""

[task.loop_3]
mode = "shell"
script = """
    for i in $(seq 1 10); do
        echo 3
        sleep 1
    done
"""

[task.incrementing]
mode = "shell"
script = """
    for i in $(seq 1 10); do
        echo $i
        sleep 1
    done
"""

[task.incrementing-sequential]
mode = "sequential"
tasks = ["incrementing", "incrementing", "incrementing"]

[task.sequential-echos]
mode = "sequential"
tasks = ["loop_1", "loop_2", "loop_3"]

[task.sequential-echos-watch]
mode = "watch"
task = "sequential-echos"
watch_list = ["src/**/*.rs"]

[task.incrementing-sequential-watch]
mode = "watch"
task = "incrementing-sequential"
watch_list = ["src/**/*.rs"]

[task.greet]
mode = "sequential"
tasks = ["echo_hello", "echo_bye"]
description = "greet to you `hello` and `bye`"

[task.greet-slow]
mode = "sequential"
tasks = ["echo_hello", "sleep", "echo_bye"]

[task.greet-parallel]
mode = "parallel"
tasks = ["greet-slow", "greet"]

[task.incrementing-watch]
mode = "watch"
task = "incrementing"
watch_list = ["src/**/*.rs"]
