[task.run]
command = "cargo"
args = ["run"]
description = "run the project"

[task.live-run]
mode = "watch"
task = "run"
watch_list = ["src/**/*.rs"]

[task.sleep]
command = "sleep"
args = ["2"]

[task.echo_hello]
command = "echo"
args = ["hello"]

[task.echo_bye]
command = "echo"
args = ["bye"]

[task.loop_1]
mode = "shell"
script = """
    for i in $(seq 1 10); do
        echo 1 $i
        sleep 1
    done
"""

[task.loop_2]
mode = "shell"
script = """
    for i in $(seq 1 10); do
        echo 2 $i
        sleep 1
    done
"""

[task.loop_3]
mode = "shell"
script = """
    for i in $(seq 1 10); do
        echo 3 $i
        sleep 1
    done
"""

[task.incl10]
mode = "shell"
script = """
    for i in $(seq 1 10); do
        echo $i
        sleep 1
    done
"""

[task.incl10-sequential]
mode = "sequential"
tasks = ["incl10", "incl10", "incl10"]

[task.sequential-echos]
mode = "sequential"
tasks = ["loop_1", "loop_2", "loop_3"]

[task.sequential-echos-watch]
mode = "watch"
task = "sequential-echos"
watch_list = ["src/**/*.rs"]

[task.incl10-sequential-watch]
mode = "watch"
task = "incl10-sequential"
watch_list = ["src/**/*.rs"]

[task.greet]
mode = "sequential"
tasks = ["echo_hello", "echo_bye"]
description = "greet to you `hello` and `bye`"

[task.greet-slow]
mode = "sequential"
tasks = ["echo_hello", "sleep", "echo_bye"]

[task.greet-parallel]
mode = "parallel"
tasks = ["greet-slow", "greet"]

[task.incl10-parallel]
mode = "parallel"
tasks = ["incl10", "incl10"]

[task.incl10-parallel-watch]
mode = "watch"
task = "incl10-parallel"
watch_list = ["src/**/*.rs"]

[task.incl10-watch]
mode = "watch"
task = "incl10"
watch_list = ["src/**/*.rs"]
