[job.cargo-run]
command = "cargo"
args = ["run"]
description = "run the project"

[job.watch-cargo-run]
mode = "watch"
job = "cargo-run"
watch_list = ["src/**", "Cargo.toml"]

[job.cargo-test]
command = "cargo"
args = ["test"]
description = "run the tests"

[job.watch-cargo-test]
mode = "watch"
job = "cargo-test"
watch_list = ["src/**", "Cargo.toml"]
